/**
 * menu.js
 * AUTO-GENERATED by Menu Builder — do not edit by hand.
 * Rendering logic ONLY. Menu content lives in menu-data.js.
 *
 * Usage (in your static page, in this order):
 *   <link rel="stylesheet" href="menu.css">
 *   <script src="menu-data.js"></script>
 *   <script src="menu.js"></script>
 *
 * Renders into the first element matching [data-menu-root],
 * or appends a new <nav> to <body> if none is found.
 */
(function () {
  "use strict";

  /**
   * Resolves a menu item URL against BASE_URL.
   * Absolute URLs (http:// or https://) pass through unchanged.
   */
  function resolveUrl(baseUrl, url) {
    const u = (url || "").trim();
    if (/^https?:\/\//i.test(u)) return u;
    const base = (baseUrl || "").trim();
    if (!base) return u;
    const normalizedBase = base.endsWith("/") ? base : base + "/";
    return normalizedBase + u.replace(/^\/+/, "");
  }

  function buildDropdown(category, idx) {
    const visibleItems = (category.items || [])
      .filter((i) => i.visible)
      .sort((a, b) => a.order - b.order);

    if (visibleItems.length === 0) {
      // No children: render as a plain nav link
      return `<li class="nav-item">
        <a class="nav-link" href="${resolveUrl(BASE_URL, category.url || '#')}">${category.name}</a>
      </li>`;
    }

    const dropdownId = `navMenuDropdown${idx}`;
    const itemsHtml = visibleItems
      .map(
        (item) => `<li>
          <a class="dropdown-item" href="${resolveUrl(BASE_URL, item.url)}" title="${item.description ? item.description.replace(/"/g, '&quot;') : ''}">${item.name}</a>
        </li>`
      )
      .join("");

    return `<li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="#" id="${dropdownId}" role="button"
         data-bs-toggle="dropdown" aria-expanded="false">
        ${category.name}
      </a>
      <ul class="dropdown-menu" aria-labelledby="${dropdownId}">
        ${itemsHtml}
      </ul>
    </li>`;
  }

  function render() {
    const visibleCats = (typeof MENU_DATA !== "undefined" ? MENU_DATA : [])
      .filter((c) => c.visible)
      .sort((a, b) => a.order - b.order);

    const linksHtml = visibleCats.map(buildDropdown).join("");

    const navHtml = `
    <nav class="navbar navbar-expand-lg sticky-top" data-menu-generated>
      <div class="container-fluid">
        <a class="navbar-brand" href="${resolveUrl(BASE_URL, "index.html")}">Site</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#generatedNavbarCollapse" aria-controls="generatedNavbarCollapse"
                aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="generatedNavbarCollapse">
          <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
            ${linksHtml}
          </ul>
        </div>
      </div>
    </nav>`;

    let root = document.querySelector("[data-menu-root]");
    if (!root) {
      root = document.createElement("div");
      root.setAttribute("data-menu-root", "");
      document.body.insertBefore(root, document.body.firstChild);
    }
    root.innerHTML = navHtml;
  }

  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", render);
  } else {
    render();
  }
})();
