/**
 * menu-data.js
 * AUTO-GENERATED by Menu Builder — do not edit by hand.
 * Generated: 2026-07-10T07:06:16.177Z
 *
 * Contains ONLY the menu data. Rendering logic lives in menu.js.
 */

// Prepended to any menu item URL that is not already absolute (http:// or https://)
const BASE_URL = 'https://agreeable-tree-017e53f10.7.azurestaticapps.net/';

const MENU_DATA = [
  {
    name: 'Home',
    order: 1,
    visible: true,
    items: [

    ]
  },
  {
    name: 'Islam',
    order: 2,
    visible: true,
    items: [
      {
        name: 'Prayer Times',
        url: 'https://matwproject.org/namaz-times/salah-time-doha',
        order: 1,
        visible: true,
        description: 'Daily Salah timings'
      },
      {
        name: 'Katara Activity',
        url: 'Activity.html',
        order: 2,
        visible: true,
        description: 'Read and study the Quran'
      }
    ]
  }
];
